version: '3.3'
services:
    app:
        image: outbound.docker.lamoda.ru/datamatrix-camunda
        ports:
            - 8080:8080
        volumes:
            - ./:/app
        depends_on:
            - postgres
        command: sh -c "java -jar target/datamatrix-0.0.1-SNAPSHOT.jar"
    postgres:
        image: postgres:12-alpine
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
volumes:
    pgdata:
