version: '3.3'
services:
    camunda:
        image: outbound.docker.lamoda.ru/datamatrix-camunda
        ports:
            - 80:8080
            - 8000:8000
        volumes:
            - ./:/app
            - springdata:/home/spring
        command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar target/datamatrix-0.0.1-SNAPSHOT.jar
    postgres:
        image: postgres:12-alpine
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
volumes:
    pgdata:
    springdata:
